<a href="https://colab.research.google.com/github/anmolkohli18/machine-learning-using-tensorflow-cookbook/blob/main/Create_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fixed Size Tensors

In [1]:
import tensorflow as tf

In [3]:
row_dim, col_dim = 3, 3
zero_tsr = tf.zeros(shape=[row_dim, col_dim], dtype=tf.float32)
zero_tsr

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [4]:
ones_tsr = tf.ones([row_dim, col_dim])
ones_tsr

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [5]:
filled_tsr = tf.fill([row_dim, col_dim], 42)
filled_tsr

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[42, 42, 42],
       [42, 42, 42],
       [42, 42, 42]], dtype=int32)>

In [7]:
constant_tsr = tf.constant([1, 2, 3])
constant_tsr

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

## Tensors of similar shape

In [8]:
zeros_similar = tf.zeros_like(constant_tsr)
zeros_similar

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [10]:
ones_similar = tf.ones_like(constant_tsr)
ones_similar

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 1, 1], dtype=int32)>

## Sequence Tensors

In [11]:
linear_tsr = tf.linspace(start=0.0, stop=1.0, num=3)
linear_tsr

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0. , 0.5, 1. ], dtype=float32)>

In [12]:
integer_seq_tsr = tf.range(start=6, limit=15, delta=3)
integer_seq_tsr

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6,  9, 12], dtype=int32)>

## Random Tensors

In [13]:
randunif_tsr = tf.random.uniform([row_dim, col_dim], minval=0, maxval=1)
randunif_tsr

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.4984511 , 0.30147958, 0.16299558],
       [0.11127651, 0.4729067 , 0.5035111 ],
       [0.29714596, 0.5416248 , 0.9357176 ]], dtype=float32)>

In [14]:
randnorm_tsr = tf.random.normal([row_dim, col_dim], mean=0.0, stddev=1.0)
randnorm_tsr

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.3808998 , -2.1827366 , -0.20980969],
       [-0.5894854 ,  0.7882922 ,  0.38114628],
       [-1.2435136 , -1.2945635 ,  0.1186499 ]], dtype=float32)>

In [16]:
rand_trunc_norm_tsr = tf.random.truncated_normal([row_dim, col_dim],
                                                 mean=0.0, stddev=1.0)
rand_trunc_norm_tsr

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.77390325,  0.84883064, -0.8795695 ],
       [ 0.18934451,  1.9380071 ,  0.67222315],
       [-0.39778146, -0.95633554, -0.6337329 ]], dtype=float32)>

In [20]:
input_tensor = tf.convert_to_tensor([1.0, 2.0, 3.0, 4.0], dtype=tf.float32)
shuffled_output = tf.random.shuffle(input_tensor)
shuffled_output

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([4., 2., 1., 3.], dtype=float32)>

## Cropping Images

In [27]:
crop_size = (1, 2)
input_tensor = tf.convert_to_tensor([[1.0, 2.0, 3.0],
                                     [3.0, 4.0, 6.0],
                                     [5.0, 7.0, 9.0]], dtype=tf.float32)
cropped_output = tf.image.random_crop(input_tensor, crop_size)
cropped_output

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[7., 9.]], dtype=float32)>

In [30]:
height, width = (64, 64)
my_image = tf.random.uniform([height, width, 3], minval=0,
                             maxval=255, dtype=tf.int32)
cropped_image = tf.image.random_crop(my_image, [height // 2, width // 2, 3])
my_image.shape, cropped_image.shape

(TensorShape([64, 64, 3]), TensorShape([32, 32, 3]))